[{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(14) tid(594) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(15) tid(5e4) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(16) tid(780) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(17) tid(7e8) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(18) tid(77c) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(19) tid(778) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(20) tid(77c) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(21) tid(77c) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(22) tid(41c) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(23) tid(754) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(24) tid(6b0) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(25) tid(624) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(26) tid(2c8) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use.\r\nDocker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__24.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nCommand exit code: 126\r\nCommand output: container 0814d2e0a5266c19bcfd8959561d48dcb7e7061384d0974562e7ac2454388798 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The directory name is invalid. (0x10b)\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]\r\n[Event Detail: onecore\\vm\\compute\\management\\orchestration\\vmhostedcontainer\\processmanagement.cpp(173)\\vmcomputeagent.exe!00007FF6278A9D2B: (caller: 00007FF62785E13A) Exception(27) tid(5e8) 8007010B The directory name is invalid.\r\n    CallContext:[\\Bridge_ProcessMessage\\VmHostedContainer_ExecuteProcess] \r\n Provider: 00000000-0000-0000-0000-000000000000] extra info: {\"CommandLine\":\"cmd /C \\\"IF EXIST C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe C:\\\\remote_debugger\\\\x64\\\\utils\\\\KillProcess.exe dotnet.exe\\\"\",\"User\":\"ContainerUser\",\"WorkingDirectory\":\"C:\\\\app\",\"Environment\":{\"ASPNETCORE_ENVIRONMENT\":\"Development\",\"ASPNETCORE_URLS\":\"http://+:80\",\"DOTNET_RUNNING_IN_CONTAINER\":\"true\",\"DOTNET_USE_POLLING_FILE_WATCHER\":\"1\",\"NUGET_FALLBACK_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\",\"NUGET_PACKAGES\":\"c:\\\\.nuget\\\\fallbackpackages\"},\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}\r\nCommand error: \r\n"}]